### ISSUE TITLE
What does `:(idle):0` represent in CPU profiles?

### ISSUE THREAD

**Issue by ldx** [grafana/pyroscope-nodejs#20]
I'm profiling a node application, and most of the CPU time is spent in this state. The process uses ~60% of one CPU core according to system metrics (this is in Kubernetes). I'm wondering what it means exactly?

![image](https://user-images.githubusercontent.com/456904/187955341-c51ac45b-70ee-435d-9696-e37900ded9a6.png)

**Comment by kolesnikovae** [comment]
We use V8's CPU profiler which is a wall time profiler. `(idle)` represents Node idle phase, which accounts for the off-CPU time
