### ISSUE TITLE
feat: `/debug/pprof/allocs` instead of `/debug/pprof/heap`

### ISSUE THREAD

**Issue by jjangga0214** [grafana/pyroscope-nodejs#36]
Hi!

It seems my Pyroscope scraps `/debug/pprof/allocs` instead of `/debug/pprof/heap`.
(I am new to Pyroscope)

Then shouldn't the express middleware handle `/debug/pprof/allocs`?

Thanks.

**Comment by simonswine** [comment]
I do think the pulling end needs to be fixed instead. As for nodejs we don't have memory allocation statistics.

**Comment by jjangga0214** [comment]
@simonswine Got it. Is it a bug of pulling end, or a thing that should be configured from pulling end? Thanks.
