### ISSUE TITLE
Update axios version to a minimum of v1.6.4

### ISSUE THREAD

**Issue by sandeepdsvs** [grafana/pyroscope-nodejs#60]
Hi,
Current version of axios used have some vulnerabilities reported by snyk. Would request you to update the version to a minimum of 1.6.4 to address them.
Thank you. Will be waiting for your response.

**Comment by simonswine** [comment]
Axios v0.28.0 has those vulnerabilities fixed: https://github.com/axios/axios/releases/tag/v0.28.0
