### ISSUE TITLE
PPROF: AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by GeoffreyPlitt** [grafana/pyroscope-nodejs#61]
[NodeJS 18.19.0, Mac Mini M1 (Apple Silicon) on OS X Sonoma 14.2.1 (23C71), pnpm 8.15.3]

Can't add package to repo, getting pprof errors below.

I add `"@pyroscope/nodejs": "^0.2.6",` or `"@pyroscope/nodejs": "^0.2.9",` to package.json, and then do `pnpm install`...

Progress: resolved 2287, reused 2246, downloaded 0, added 0, done
node_modules/.pnpm/pprof@4.0.0/node_modules/pprof: Running install script, failed in 1s
.../.pnpm/pprof@4.0.0/node_modules/pprof install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@1.0.11
│ node-pre-gyp info using node@18.19.0 | darwin | arm64
│ node-pre-gyp info check checked for "/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@4.0.0/node_modules/pprof/build/node-v108-darwin-arm64-unknown/p…
│ node-pre-gyp http GET https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v4.0.0/node-v108-darwin-arm64-unknown.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v4.0.0/node-v108-darwin-arm64-unknown.tar…
│ node-pre-gyp WARN Pre-built binaries not installable for pprof@4.0.0 and node@18.19.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v4.0.0/node-v108-darwin-arm64-unknown.t…
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@18.19.0 | darwin | arm64
│ gyp info ok 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@18.19.0 | darwin | arm64
│ gyp info find Python using Python version 3.11.4 found at "/Users/giro/miniconda3/bin/python3"
│ gyp info spawn /Users/giro/miniconda3/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@4.0.0/node_modules/pprof/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/giro/Library/Caches/node-gyp/18.19.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/giro/Library/Caches/node-gyp/18.19.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/giro/Library/Caches/node-gyp/18.19.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@4.0.0/node_modules/pprof',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
│ Traceback (most recent call last):
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, in XcodeVersion
│     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
│                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
│     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
│ gyp.common.GypError: Error 1 running xcodebuild
│ During handling of the above exception, another exception occurred:
│ Traceback (most recent call last):
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
│     sys.exit(gyp.script_main())
│              ^^^^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 686, in script_main
│     return main(sys.argv[1:])
│            ^^^^^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 678, in main
│     return gyp_main(args)
│            ^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 663, in gyp_main
│     generator.GenerateOutput(flat_list, targets, data, params)
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2651, in GenerateOutput
│     writer.Write(
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 902, in Write
│     self.WriteCopies(spec["copies"], extra_outputs, part_of_all)
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1298, in WriteCopies
│     env = self.GetSortedXcodeEnv()
│           ^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2269, in GetSortedXcode…
│     return gyp.xcode_emulation.GetSortedXcodeEnv(
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1888, in GetSortedXcod…
│     env = _GetXcodeEnv(
│           ^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1743, in _GetXcodeEnv
│     "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
│                             ^^^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, in XcodeVersion
│     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
│               ^^^^^^^^^^^^
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, in CLTVersion
│     return re.search(regex, output).groupdict()["version"]
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│ AttributeError: 'NoneType' object has no attribute 'groupdict'
│ gyp ERR! configure error 
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:325:16)
│ gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
│ gyp ERR! System Darwin 23.2.0
│ gyp ERR! command "/Users/giro/Library/pnpm/nodejs/18.19.0/bin/node" "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/b…
│ gyp ERR! cwd /Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@4.0.0/node_modules/pprof
│ gyp ERR! node -v v18.19.0
│ gyp ERR! node-gyp -v v9.4.1
│ gyp ERR! not ok 
│ node-pre-gyp ERR! build error 
│ node-pre-gyp ERR! stack Error: Failed to execute '/Users/giro/Library/pnpm/nodejs/18.19.0/bin/node /Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnp…
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/…
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
│ node-pre-gyp ERR! System Darwin 23.2.0
│ node-pre-gyp ERR! command "/Users/giro/Library/pnpm/nodejs/18.19.0/bin/node" "/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/…
│ node-pre-gyp ERR! cwd /Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@4.0.0/node_modules/pprof
│ node-pre-gyp ERR! node -v v18.19.0
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.11
│ node-pre-gyp ERR! not ok 
│ Failed to execute '/Users/giro/Library/pnpm/nodejs/18.19.0/bin/node /Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.15.3/node_modules/pnpm/dist/node_modules/node-gyp/bi…
└─ Failed in 1s at /Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@4.0.0/node_modules/pprof
 ELIFECYCLE  Command failed with exit code 1.

**Comment by simonswine** [comment]
I am not an expert on pnpm and/or node package management, but if I read the logs correctly it uses a python version installed in `/Users/giro/miniconda3/bin/python3`. I wonder if that is the issue.

Reading up on the node-gyp docs at https://github.com/nodejs/node-gy, I think that forcing the choice of python might resolve this problem:

```
export npm_config_python=/usr/bin/python3
```

Let me know how you are getting on.

**Comment by GeoffreyPlitt** [comment]
I followed your instructions and got nearly the same result (although you can see it's using a different path for python now):

`pn i
Lockfile is up to date, resolution step is skipped
Packages: +297 -158
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------------------------------------------
Progress: resolved 282, reused 280, downloaded 0, added 0, done
node_modules/.pnpm/pprof@3.2.1/node_modules/pprof: Running install script, failed in 968ms
.../.pnpm/pprof@3.2.1/node_modules/pprof install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@1.0.11
│ node-pre-gyp info using node@18.18.2 | darwin | arm64
│ node-pre-gyp info check checked for "/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/pprof/build/node-v108-darwin-arm64-unknown/pprof.node" (not found)
│ node-pre-gyp http GET https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.1/node-v108-darwin-arm64-unknown.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.1/node-v108-darwin-arm64-unknown.tar.gz 
│ node-pre-gyp WARN Pre-built binaries not installable for pprof@3.2.1 and node@18.18.2 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.1/node-v108-darwin-arm64-unknown.tar.gz 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@18.18.2 | darwin | arm64
│ gyp info ok 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@18.18.2 | darwin | arm64
│ gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
│ gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/pprof/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/giro/Library/Caches/node-gyp/18.18.2/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/giro/Library/Caches/node-gyp/18.18.2',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/giro/Library/Caches/node-gyp/18.18.2/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/pprof',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
│ Traceback (most recent call last):
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, in XcodeVersion
│     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
│     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
│ gyp.common.GypError: Error 1 running xcodebuild
│ During handling of the above exception, another exception occurred:
│ Traceback (most recent call last):
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
│     sys.exit(gyp.script_main())
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 686, in script_main
│     return main(sys.argv[1:])
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 678, in main
│     return gyp_main(args)
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 663, in gyp_main
│     generator.GenerateOutput(flat_list, targets, data, params)
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2651, in GenerateOutput
│     writer.Write(
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 902, in Write
│     self.WriteCopies(spec["copies"], extra_outputs, part_of_all)
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1298, in WriteCopies
│     env = self.GetSortedXcodeEnv()
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2269, in GetSortedXcodeEnv
│     return gyp.xcode_emulation.GetSortedXcodeEnv(
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1888, in GetSortedXcodeEnv
│     env = _GetXcodeEnv(
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1743, in _GetXcodeEnv
│     "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, in XcodeVersion
│     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
│   File "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, in CLTVersion
│     return re.search(regex, output).groupdict()["version"]
│ AttributeError: 'NoneType' object has no attribute 'groupdict'
│ gyp ERR! configure error 
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:325:16)
│ gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
│ gyp ERR! System Darwin 23.4.0
│ gyp ERR! command "/Users/giro/Library/pnpm/nodejs/18.18.2/bin/node" "/Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/giro/auditboar…
│ gyp ERR! cwd /Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/pprof
│ gyp ERR! node -v v18.18.2
│ gyp ERR! node-gyp -v v9.4.1
│ gyp ERR! not ok 
│ node-pre-gyp ERR! build error 
│ node-pre-gyp ERR! stack Error: Failed to execute '/Users/giro/Library/pnpm/nodejs/18.18.2/bin/node /Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --modu…
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
│ node-pre-gyp ERR! System Darwin 23.4.0
│ node-pre-gyp ERR! command "/Users/giro/Library/pnpm/nodejs/18.18.2/bin/node" "/Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
│ node-pre-gyp ERR! cwd /Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/pprof
│ node-pre-gyp ERR! node -v v18.18.2
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.11
│ node-pre-gyp ERR! not ok 
│ Failed to execute '/Users/giro/Library/pnpm/nodejs/18.18.2/bin/node /Users/giro/Library/pnpm/global/5/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/giro/auditboard-dev-e…
└─ Failed in 968ms at /Users/giro/auditboard-dev-env/soxhub-api/node_modules/.pnpm/pprof@3.2.1/node_modules/pprof
 ELIFECYCLE  Command failed with exit code 1.`

Looking deeper, I think the problem is a bug in node-gyp: https://github.com/nodejs/node-gyp/issues/2992

**Comment by cclauss** [comment]
Please try: `NODE_GYP_FORCE_PYTHON=python3 <your command goes here>`
* So in your case... `NODE_GYP_FORCE_PYTHON=python3 node-pre-gyp install --fallback-to-build`

From: https://github.com/nodejs/node-gyp/issues/2144#issuecomment-636496546

**Comment by simonswine** [comment]
It is still not able to find your CLI/Xcode verison: Do you also mind to run those commands for me and share the output:

```
$ /usr/sbin/softwareupdate --history

$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables

$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI

$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLILeo
```

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/main/macOS_Catalina_acid_test.sh

**Comment by GeoffreyPlitt** [comment]
@simonswine 

(base) giro@Geoffs-Mac-mini: ~/auditboard-dev-env/soxhub-api$ /usr/sbin/softwareupdate --history
Display Name                                       Version    Date                  
------------                                       -------    ----                  
macOS Sonoma 14.4                                  14.4       03/09/2024, 10:28:49  
(base) giro@Geoffs-Mac-mini: ~/auditboard-dev-env/soxhub-api$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
(base) giro@Geoffs-Mac-mini: ~/auditboard-dev-env/soxhub-api$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
(base) giro@Geoffs-Mac-mini: ~/auditboard-dev-env/soxhub-api$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLILeo
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

**Comment by simonswine** [comment]
@GeoffreyPlitt the all of those commands can't find a trace of XCode or command line tools being installed. 

Can you double check the steps outline here (also post e.g. the CLI output of it):

This is what I am getting:

```
$ xcode-select --install
xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates
```


![image](https://github.com/grafana/pyroscope-nodejs/assets/223048/2d9e33f7-e254-4d12-ba9d-06f48142d7cc)

**Comment by cclauss** [comment]
On my M1 Mac:
% ` /usr/sbin/pkgutil --pkgs-plist | grep CL
```
	<string>com.apple.pkg.CLTools_SDK_macOS13</string>
	<string>com.apple.pkg.CLTools_SDK_macOS12</string>
	<string>com.apple.pkg.CLTools_Executables</string>
	<string>com.apple.pkg.CLTools_SDK_macOS14</string>
	<string>com.apple.pkg.CLTools_SwiftBackDeploy</string>
	<string>com.apple.pkg.CLTools_macOS_SDK</string>
```
What is your output from this command?

**Comment by GeoffreyPlitt** [comment]
Thanks for the help, guys.

```giro@Geoffs-Mac-mini: ~$ uname -a
Darwin Geoffs-Mac-mini.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103 arm64
giro@Geoffs-Mac-mini: ~$ sw_vers
ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
giro@Geoffs-Mac-mini: ~$ xcode-select --install                  
xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates
giro@Geoffs-Mac-mini: ~$ /usr/sbin/pkgutil --pkgs-plist | grep CL
giro@Geoffs-Mac-mini: ~$```

Looks like pkgutil seems to not be able to find those packages you see.  I'm not sure why.

**Comment by cclauss** [comment]
Yes, please.

**Comment by GeoffreyPlitt** [comment]
This worked! Wow, you guys went above and beyond in helping with this. Thank you so much!!!
